#!/bin/bash

set -o errexit
set -o nounset

worker_ready(){
    celery -A app.celery inspect ping
}

until worker_ready; do
    >&2 echo 'Celery workers are not available.'
    sleep 1
done

>&2 echo 'Celery worker available.'

celery -A app.celery \
    --broker="${CELERY_BROKER_URL}" \
    flower